ports:
  - port: 8080
    onOpen: open-preview
checkoutLocation: "go/src/github.com/gyuhwankim/go-gin-starterkit"
workspaceLocation: "go/src/github.com/gyuhwankim/go-gin-starterkit"
tasks:
  - init: >
      go get -v ./... &&
      go build -o app
github:
    prebuilds:
        pullRequestsFromForks: true
