ports:
  - port: 8080
    onOpen: open-preview
checkoutLocation: "go/src/github.com/gyuhwankim/go-gin-starterkit"
workspaceLocation: "go/src/github.com/gyuhwankim/go-gin-starterkit"
tasks:
  - init: >
      export GO111MODULE=on &&
      go mod download
github:
    prebuilds:
        pullRequestsFromForks: true
