version: "3.7"
services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      - REST_ADDR=:8080
      - REST_POSTGRES_DRIVER=postgres
      - REST_POSTGRES_HOST=postgres
      - REST_POSTGRES_PORT=5432
      - REST_POSTGRES_USER=postgres
      - REST_POSTGRES_NAME=postgres
      - REST_POSTGRES_PASSWORD=postgres
    depends_on:
      - postgres
  postgres:
    image: postgres:11.3-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
