version: "3.7"
services:
  test_postgres:
    image: postgres:11.3-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5431:5432
