version: "3.7"
services:
  redis:
    image: redis:5.0.5-alpine
    ports:
      - 6378:6379
  postgres:
    image: postgres:11.3-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5431:5432
