version: 2
jobs:
    build:
        docker:
            - image: circleci/golang:1.12
        working_directory: /go-gin-starterkit
        steps:
            - checkout

workflows:
    version: 2
    build-test:
        jobs:
            - build