version: 2
jobs:
    build:
        docker:
            - image: circleci/golang:1.12
              environment:
                  GO111MODULE: "ON"
        working_directory: /go/src/github.com/gyuhwankim/go-gin-starterkit
        steps:
            - checkout

            - run: go download
            - run: go build

workflows:
    version: 2
    build-test:
        jobs:
            - build