version: 2
jobs:
    build-binary:
        docker:
            - image: circleci/golang:1.12
        working_directory: ~/go-gin-starterkit
        steps:
          - checkout

          - restore_cache:
              keys: 
                - go-mod-v1-{{ checksum "go.sum" }}

          - run: go build

          - save_cache:
              key: go-mod-v1-{{ checksum "go.sum" }}
              paths:
                - "/go/pkg/mod"

    build-docker-image:
        machine: true
        working_directory: ~/go-gin-starterkit
        steps:
            - checkout
            - run: docker build -t go-gin-starterkit .
            - run: mkdir -p /tmp/images
            - run: docker save -o /tmp/images/app.tar go-gin-starterkit
            - store_artifacts:
                path: /tmp/images
                destination: app.tar

    run-unittest:
        docker:
            - image: circleci/golang:1.12
        working_directory: ~/go-gin-starterkit
        steps:
          - checkout

          - restore_cache:
              keys: 
                - go-mod-v1-{{ checksum "go.sum" }}
              
          - run: make unit

          - save_cache:
              key: go-mod-v1-{{ checksum "go.sum" }}
              paths:
                - "/go/pkg/mod"

    run-integration:
        machine:
          image: circleci/classic:201808-01
          docker_layer_caching: true
        steps:
          - checkout
          - run:
              name: Install Go 1.12.5
              command: |
                curl -L https://storage.googleapis.com/golang/go1.12.5.linux-amd64.tar.gz > ~/go.tar.gz
                sudo tar -C ~ -xvf ~/go.tar.gz 1> /dev/null
                sudo rm -rf /usr/local/go
                sudo mv ~/go /usr/local
        
          - restore_cache:
              keys: 
                - go-mod-v1-{{ checksum "go.sum" }}

          - run: make integration

          - save_cache:
              key: go-mod-v1-{{ checksum "go.sum" }}
              paths:
                - "/go/pkg/mod"
    
workflows:
    version: 2
    build-test:
        jobs:
            - build-binary
            - build-docker-image
            - run-unittest:
                requires:
                  - build-binary
            - run-integration:
                requires:
                  - build-binary
            - build-docker-image:
                requires:
                  - run-unittest
                  - run-integration